/**
 * SocketCAN Neon Rust - JavaScript API
 * 
 * This file is automatically generated from TypeScript sources.
 * Do not edit this file directly - edit the TypeScript sources in src/ instead.
 * 
 * To regenerate this API: npm run generate-js
 */

// Forward to the compiled TypeScript API
module.exports = require('./dist/src/main.js');
